matrix:
  include:
    - language: php
      php: 5.6
      before_script:
        - cd ${TRAVIS_BUILD_DIR}
        - find . -type f -name *.php | xargs -n1 php -l
      script:
        - /bin/bash ./test/testPhp.bash
      after_success:
        - coveralls

    - language: python
      python: 2.7
      install:
        - pip install lxml requests python-daemon
      script:
        - /bin/bash ./test/testFtpd.bash
      after_success:
        - coveralls

    - language: markdown
      addons:
        apt:
          packages:
            - aspell
            - aspell-fr
      script:
        - /bin/bash ./test/spellCheckMD.bash
        - /bin/bash ./test/checkMD.bash
      after_success:
        - coveralls
